//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SupplierService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WebsiteUrl {
            get {
                return this.WebsiteUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteUrlField, value) != true)) {
                    this.WebsiteUrlField = value;
                    this.RaisePropertyChanged("WebsiteUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierService.SupplierServiceSoap")]
    public interface SupplierServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.SupplierService.HelloWorldResponse HelloWorld(Client.SupplierService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierService.HelloWorldResponse> HelloWorldAsync(Client.SupplierService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        Client.SupplierService.AddSupplierResponse AddSupplier(Client.SupplierService.AddSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierService.AddSupplierResponse> AddSupplierAsync(Client.SupplierService.AddSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        Client.SupplierService.UpdateSupplierResponse UpdateSupplier(Client.SupplierService.UpdateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierService.UpdateSupplierResponse> UpdateSupplierAsync(Client.SupplierService.UpdateSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        void DeleteSupplier(int supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteSupplierAsync(int supplierId);
        
        // CODEGEN: Generating message contract since element name GetSupplierByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierById", ReplyAction="*")]
        Client.SupplierService.GetSupplierByIdResponse GetSupplierById(Client.SupplierService.GetSupplierByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierById", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierService.GetSupplierByIdResponse> GetSupplierByIdAsync(Client.SupplierService.GetSupplierByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSuppliersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        Client.SupplierService.GetAllSuppliersResponse GetAllSuppliers(Client.SupplierService.GetAllSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SupplierService.GetAllSuppliersResponse> GetAllSuppliersAsync(Client.SupplierService.GetAllSuppliersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.SupplierService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.SupplierService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.AddSupplierRequestBody Body;
        
        public AddSupplierRequest() {
        }
        
        public AddSupplierRequest(Client.SupplierService.AddSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contactEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contactPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string websiteUrl;
        
        public AddSupplierRequestBody() {
        }
        
        public AddSupplierRequestBody(string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            this.name = name;
            this.contactEmail = contactEmail;
            this.contactPhone = contactPhone;
            this.address = address;
            this.websiteUrl = websiteUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.AddSupplierResponseBody Body;
        
        public AddSupplierResponse() {
        }
        
        public AddSupplierResponse(Client.SupplierService.AddSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddSupplierResponseBody {
        
        public AddSupplierResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplier", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.UpdateSupplierRequestBody Body;
        
        public UpdateSupplierRequest() {
        }
        
        public UpdateSupplierRequest(Client.SupplierService.UpdateSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contactEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contactPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string websiteUrl;
        
        public UpdateSupplierRequestBody() {
        }
        
        public UpdateSupplierRequestBody(int supplierId, string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            this.supplierId = supplierId;
            this.name = name;
            this.contactEmail = contactEmail;
            this.contactPhone = contactPhone;
            this.address = address;
            this.websiteUrl = websiteUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.UpdateSupplierResponseBody Body;
        
        public UpdateSupplierResponse() {
        }
        
        public UpdateSupplierResponse(Client.SupplierService.UpdateSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateSupplierResponseBody {
        
        public UpdateSupplierResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupplierByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupplierById", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.GetSupplierByIdRequestBody Body;
        
        public GetSupplierByIdRequest() {
        }
        
        public GetSupplierByIdRequest(Client.SupplierService.GetSupplierByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSupplierByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public GetSupplierByIdRequestBody() {
        }
        
        public GetSupplierByIdRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupplierByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupplierByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.GetSupplierByIdResponseBody Body;
        
        public GetSupplierByIdResponse() {
        }
        
        public GetSupplierByIdResponse(Client.SupplierService.GetSupplierByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSupplierByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.SupplierService.Supplier GetSupplierByIdResult;
        
        public GetSupplierByIdResponseBody() {
        }
        
        public GetSupplierByIdResponseBody(Client.SupplierService.Supplier GetSupplierByIdResult) {
            this.GetSupplierByIdResult = GetSupplierByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.GetAllSuppliersRequestBody Body;
        
        public GetAllSuppliersRequest() {
        }
        
        public GetAllSuppliersRequest(Client.SupplierService.GetAllSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSuppliersRequestBody {
        
        public GetAllSuppliersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.SupplierService.GetAllSuppliersResponseBody Body;
        
        public GetAllSuppliersResponse() {
        }
        
        public GetAllSuppliersResponse(Client.SupplierService.GetAllSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.SupplierService.Supplier[] GetAllSuppliersResult;
        
        public GetAllSuppliersResponseBody() {
        }
        
        public GetAllSuppliersResponseBody(Client.SupplierService.Supplier[] GetAllSuppliersResult) {
            this.GetAllSuppliersResult = GetAllSuppliersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierServiceSoapChannel : Client.SupplierService.SupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierServiceSoapClient : System.ServiceModel.ClientBase<Client.SupplierService.SupplierServiceSoap>, Client.SupplierService.SupplierServiceSoap {
        
        public SupplierServiceSoapClient() {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierService.HelloWorldResponse Client.SupplierService.SupplierServiceSoap.HelloWorld(Client.SupplierService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.SupplierService.HelloWorldRequest inValue = new Client.SupplierService.HelloWorldRequest();
            inValue.Body = new Client.SupplierService.HelloWorldRequestBody();
            Client.SupplierService.HelloWorldResponse retVal = ((Client.SupplierService.SupplierServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierService.HelloWorldResponse> Client.SupplierService.SupplierServiceSoap.HelloWorldAsync(Client.SupplierService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierService.HelloWorldResponse> HelloWorldAsync() {
            Client.SupplierService.HelloWorldRequest inValue = new Client.SupplierService.HelloWorldRequest();
            inValue.Body = new Client.SupplierService.HelloWorldRequestBody();
            return ((Client.SupplierService.SupplierServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierService.AddSupplierResponse Client.SupplierService.SupplierServiceSoap.AddSupplier(Client.SupplierService.AddSupplierRequest request) {
            return base.Channel.AddSupplier(request);
        }
        
        public void AddSupplier(string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            Client.SupplierService.AddSupplierRequest inValue = new Client.SupplierService.AddSupplierRequest();
            inValue.Body = new Client.SupplierService.AddSupplierRequestBody();
            inValue.Body.name = name;
            inValue.Body.contactEmail = contactEmail;
            inValue.Body.contactPhone = contactPhone;
            inValue.Body.address = address;
            inValue.Body.websiteUrl = websiteUrl;
            Client.SupplierService.AddSupplierResponse retVal = ((Client.SupplierService.SupplierServiceSoap)(this)).AddSupplier(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierService.AddSupplierResponse> Client.SupplierService.SupplierServiceSoap.AddSupplierAsync(Client.SupplierService.AddSupplierRequest request) {
            return base.Channel.AddSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierService.AddSupplierResponse> AddSupplierAsync(string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            Client.SupplierService.AddSupplierRequest inValue = new Client.SupplierService.AddSupplierRequest();
            inValue.Body = new Client.SupplierService.AddSupplierRequestBody();
            inValue.Body.name = name;
            inValue.Body.contactEmail = contactEmail;
            inValue.Body.contactPhone = contactPhone;
            inValue.Body.address = address;
            inValue.Body.websiteUrl = websiteUrl;
            return ((Client.SupplierService.SupplierServiceSoap)(this)).AddSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierService.UpdateSupplierResponse Client.SupplierService.SupplierServiceSoap.UpdateSupplier(Client.SupplierService.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplier(request);
        }
        
        public void UpdateSupplier(int supplierId, string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            Client.SupplierService.UpdateSupplierRequest inValue = new Client.SupplierService.UpdateSupplierRequest();
            inValue.Body = new Client.SupplierService.UpdateSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            inValue.Body.name = name;
            inValue.Body.contactEmail = contactEmail;
            inValue.Body.contactPhone = contactPhone;
            inValue.Body.address = address;
            inValue.Body.websiteUrl = websiteUrl;
            Client.SupplierService.UpdateSupplierResponse retVal = ((Client.SupplierService.SupplierServiceSoap)(this)).UpdateSupplier(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierService.UpdateSupplierResponse> Client.SupplierService.SupplierServiceSoap.UpdateSupplierAsync(Client.SupplierService.UpdateSupplierRequest request) {
            return base.Channel.UpdateSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierService.UpdateSupplierResponse> UpdateSupplierAsync(int supplierId, string name, string contactEmail, string contactPhone, string address, string websiteUrl) {
            Client.SupplierService.UpdateSupplierRequest inValue = new Client.SupplierService.UpdateSupplierRequest();
            inValue.Body = new Client.SupplierService.UpdateSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            inValue.Body.name = name;
            inValue.Body.contactEmail = contactEmail;
            inValue.Body.contactPhone = contactPhone;
            inValue.Body.address = address;
            inValue.Body.websiteUrl = websiteUrl;
            return ((Client.SupplierService.SupplierServiceSoap)(this)).UpdateSupplierAsync(inValue);
        }
        
        public void DeleteSupplier(int supplierId) {
            base.Channel.DeleteSupplier(supplierId);
        }
        
        public System.Threading.Tasks.Task DeleteSupplierAsync(int supplierId) {
            return base.Channel.DeleteSupplierAsync(supplierId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierService.GetSupplierByIdResponse Client.SupplierService.SupplierServiceSoap.GetSupplierById(Client.SupplierService.GetSupplierByIdRequest request) {
            return base.Channel.GetSupplierById(request);
        }
        
        public Client.SupplierService.Supplier GetSupplierById(int supplierId) {
            Client.SupplierService.GetSupplierByIdRequest inValue = new Client.SupplierService.GetSupplierByIdRequest();
            inValue.Body = new Client.SupplierService.GetSupplierByIdRequestBody();
            inValue.Body.supplierId = supplierId;
            Client.SupplierService.GetSupplierByIdResponse retVal = ((Client.SupplierService.SupplierServiceSoap)(this)).GetSupplierById(inValue);
            return retVal.Body.GetSupplierByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierService.GetSupplierByIdResponse> Client.SupplierService.SupplierServiceSoap.GetSupplierByIdAsync(Client.SupplierService.GetSupplierByIdRequest request) {
            return base.Channel.GetSupplierByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierService.GetSupplierByIdResponse> GetSupplierByIdAsync(int supplierId) {
            Client.SupplierService.GetSupplierByIdRequest inValue = new Client.SupplierService.GetSupplierByIdRequest();
            inValue.Body = new Client.SupplierService.GetSupplierByIdRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((Client.SupplierService.SupplierServiceSoap)(this)).GetSupplierByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.SupplierService.GetAllSuppliersResponse Client.SupplierService.SupplierServiceSoap.GetAllSuppliers(Client.SupplierService.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliers(request);
        }
        
        public Client.SupplierService.Supplier[] GetAllSuppliers() {
            Client.SupplierService.GetAllSuppliersRequest inValue = new Client.SupplierService.GetAllSuppliersRequest();
            inValue.Body = new Client.SupplierService.GetAllSuppliersRequestBody();
            Client.SupplierService.GetAllSuppliersResponse retVal = ((Client.SupplierService.SupplierServiceSoap)(this)).GetAllSuppliers(inValue);
            return retVal.Body.GetAllSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.SupplierService.GetAllSuppliersResponse> Client.SupplierService.SupplierServiceSoap.GetAllSuppliersAsync(Client.SupplierService.GetAllSuppliersRequest request) {
            return base.Channel.GetAllSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.SupplierService.GetAllSuppliersResponse> GetAllSuppliersAsync() {
            Client.SupplierService.GetAllSuppliersRequest inValue = new Client.SupplierService.GetAllSuppliersRequest();
            inValue.Body = new Client.SupplierService.GetAllSuppliersRequestBody();
            return ((Client.SupplierService.SupplierServiceSoap)(this)).GetAllSuppliersAsync(inValue);
        }
    }
}
